// SlimeVenture — data definitions
// Items, enemies, obstacles, locations. Kept data-driven per GDD §12.4.

export const RARITIES = {
  common: "C",
  uncommon: "U",
  rare: "R",
  legendary: "L",
};

/** Items. Shapes simplified to 1x1 for now (Tetris-style shapes are planned). */
export const ITEMS = {
  rusty_sword: {
    id: "rusty_sword",
    name: "Rusty Sword",
    emoji: "🗡️",
    rarity: "common",
    held: { attack: 2 },
    digest: { gold: 3 },
    digestTime: 8,
    tags: ["weapon", "metal"],
    flavor: "+2 attack while held.",
  },
  healing_herb: {
    id: "healing_herb",
    name: "Healing Herb",
    emoji: "🌿",
    rarity: "common",
    held: { regen: 1, regenInterval: 5 },
    digest: { heal: 10 },
    digestTime: 3,
    tags: ["organic", "healing"],
    flavor: "Regen 1 HP / 5 ticks while held.",
  },
  gold_nugget: {
    id: "gold_nugget",
    name: "Gold Nugget",
    emoji: "🪙",
    rarity: "common",
    held: null,
    digest: { gold: 15 },
    digestTime: 4,
    tags: ["mineral"],
    flavor: "Eat for +15 gold.",
  },
  flame_core: {
    id: "flame_core",
    name: "Flame Core",
    emoji: "🔥",
    rarity: "uncommon",
    held: { attack: 1 },
    digest: { heal: 2, buff: "burn_aura" },
    digestTime: 6,
    tags: ["elemental", "fire"],
    flavor: "+1 attack while held. Eat for Burn Aura.",
  },
  shield_fragment: {
    id: "shield_fragment",
    name: "Shield Fragment",
    emoji: "🛡️",
    rarity: "uncommon",
    held: { damageReduction: 1 },
    digest: { gold: 5 },
    digestTime: 10,
    tags: ["armor", "metal"],
    flavor: "-1 damage taken while held.",
  },
  slime_jelly: {
    id: "slime_jelly",
    name: "Slime Jelly",
    emoji: "🟣",
    rarity: "common",
    held: { maxHpBonus: 1 },
    digest: { heal: 5, permMaxHp: 1 },
    digestTime: 2,
    tags: ["organic", "slime"],
    flavor: "+1 max HP while held; eat for perm +1 max HP.",
  },
  bomb: {
    id: "bomb",
    name: "Bomb",
    emoji: "💣",
    rarity: "uncommon",
    held: null,
    digest: { enemyDamage: 20 },
    digestTime: 1,
    tags: ["explosive"],
    flavor: "Eat to hurl 20 dmg at the enemy in your lane.",
  },
  // --- Rare items ---
  iron_blade: {
    id: "iron_blade",
    name: "Iron Blade",
    emoji: "⚔️",
    rarity: "rare",
    held: { attack: 4 },
    digest: { gold: 8 },
    digestTime: 10,
    tags: ["weapon", "metal"],
    flavor: "+4 attack while held.",
  },
  venom_gland: {
    id: "venom_gland",
    name: "Venom Gland",
    emoji: "🧪",
    rarity: "rare",
    held: null,
    digest: { buff: "poison_coat", heal: 3 },
    digestTime: 4,
    tags: ["organic", "poison"],
    flavor: "Eat to coat yourself in venom for 12 ticks.",
  },
  frost_shard: {
    id: "frost_shard",
    name: "Frost Shard",
    emoji: "🧊",
    rarity: "rare",
    held: { damageReduction: 2 },
    digest: { buff: "shield", heal: 5 },
    digestTime: 5,
    tags: ["elemental", "ice"],
    flavor: "-2 damage taken while held. Eat for a 15-HP shield.",
  },
  life_root: {
    id: "life_root",
    name: "Life Root",
    emoji: "🌳",
    rarity: "rare",
    held: { regen: 2, regenInterval: 4 },
    digest: { heal: 20 },
    digestTime: 5,
    tags: ["organic", "healing"],
    flavor: "Regen 2 HP / 4 ticks while held.",
  },
  golden_idol: {
    id: "golden_idol",
    name: "Golden Idol",
    emoji: "🏆",
    rarity: "rare",
    held: null,
    digest: { gold: 40 },
    digestTime: 6,
    tags: ["mineral", "valuable"],
    flavor: "Eat for a big payday.",
  },
  fire_bomb: {
    id: "fire_bomb",
    name: "Fire Bomb",
    emoji: "🧨",
    rarity: "rare",
    held: null,
    digest: { enemyDamage: 35, buff: "burn_aura" },
    digestTime: 2,
    tags: ["explosive", "fire"],
    flavor: "Massive blast + burn aura.",
  },
  thorned_hide: {
    id: "thorned_hide",
    name: "Thorned Hide",
    emoji: "🦔",
    rarity: "rare",
    held: { damageReduction: 1, attack: 1 },
    digest: { gold: 6 },
    digestTime: 8,
    tags: ["armor", "organic"],
    flavor: "-1 damage taken, +1 attack while held.",
  },
  toxic_mushroom: {
    id: "toxic_mushroom",
    name: "Toxic Mushroom",
    emoji: "🍄",
    rarity: "uncommon",
    held: null,
    digest: { buff: "poison_coat", heal: 1 },
    digestTime: 2,
    tags: ["organic", "poison"],
    flavor: "Quick digest for a venom coating.",
  },
  speed_berry: {
    id: "speed_berry",
    name: "Speed Berry",
    emoji: "🫐",
    rarity: "uncommon",
    held: null,
    digest: { buff: "haste", heal: 2 },
    digestTime: 2,
    tags: ["organic"],
    flavor: "Eat for a burst of speed (8 ticks).",
  },
  acid_vial: {
    id: "acid_vial",
    name: "Acid Vial",
    emoji: "🧫",
    rarity: "uncommon",
    held: null,
    digest: { buff: "acid", heal: 1 },
    digestTime: 1,
    tags: ["elemental", "acid"],
    flavor: "Eat to double digestion speed (10 ticks).",
  },
  slime_mold: {
    id: "slime_mold",
    name: "Slime Mold",
    emoji: "🫧",
    rarity: "rare",
    held: null,
    digest: { buff: "bloat", heal: 3 },
    digestTime: 3,
    tags: ["organic", "slime"],
    flavor: "Eat to temporarily grow +2 cells (12 ticks).",
  },
  sticky_resin: {
    id: "sticky_resin",
    name: "Sticky Resin",
    emoji: "🍯",
    rarity: "uncommon",
    held: null,
    digest: { buff: "sticky", heal: 2 },
    digestTime: 2,
    tags: ["organic"],
    flavor: "Eat to send pickups straight to stomach (10 ticks).",
  },
  // --- Legendary items ---
  crystal_heart: {
    id: "crystal_heart",
    name: "Crystal Heart",
    emoji: "💎",
    rarity: "legendary",
    held: { maxHpBonus: 5, regen: 1, regenInterval: 6 },
    digest: { heal: 30, permMaxHp: 3 },
    digestTime: 8,
    tags: ["mineral", "healing"],
    flavor: "+5 max HP + regen while held.",
  },
  inferno_blade: {
    id: "inferno_blade",
    name: "Inferno Blade",
    emoji: "🌋",
    rarity: "legendary",
    held: { attack: 6 },
    digest: { enemyDamage: 50, buff: "burn_aura" },
    digestTime: 3,
    tags: ["weapon", "fire"],
    flavor: "+6 attack while held. Eat for devastating fire.",
  },
  phoenix_feather: {
    id: "phoenix_feather",
    name: "Phoenix Feather",
    emoji: "🪶",
    rarity: "legendary",
    held: { regen: 3, regenInterval: 3 },
    digest: { heal: 50 },
    digestTime: 6,
    tags: ["organic", "fire", "healing"],
    flavor: "Powerful regen while held.",
  },
  void_gem: {
    id: "void_gem",
    name: "Void Gem",
    emoji: "🔮",
    rarity: "legendary",
    held: { attack: 3, damageReduction: 3 },
    digest: { gold: 60 },
    digestTime: 12,
    tags: ["elemental", "mineral"],
    flavor: "+3 attack, -3 damage while held.",
  },
};

export const ITEM_POOL_BY_RARITY = {
  common: ["rusty_sword", "healing_herb", "gold_nugget", "slime_jelly"],
  uncommon: ["flame_core", "shield_fragment", "bomb", "toxic_mushroom", "speed_berry", "acid_vial", "sticky_resin"],
  rare: ["iron_blade", "venom_gland", "frost_shard", "life_root", "golden_idol", "fire_bomb", "thorned_hide", "slime_mold"],
  legendary: ["crystal_heart", "inferno_blade", "phoenix_feather", "void_gem"],
};

/** Enemies */
export const ENEMIES = {
  green_blob: {
    id: "green_blob",
    name: "Green Blob",
    emoji: "🟩",
    hp: 5,
    attack: 1,
    speed: 1,
    gold: 2,
    dropChance: 0,
    cost: 1,
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    emoji: "💀",
    hp: 10,
    attack: 3,
    speed: 1,
    gold: 5,
    dropChance: 0.3,
    dropPool: ["rusty_sword"],
    cost: 2,
  },
  fire_imp: {
    id: "fire_imp",
    name: "Fire Imp",
    emoji: "👺",
    hp: 8,
    attack: 2,
    speed: 1,
    gold: 3,
    dropChance: 0.25,
    dropPool: ["flame_core"],
    cost: 2,
    onDeath: { burn: 3 },
  },
  stone_golem: {
    id: "stone_golem",
    name: "Stone Golem",
    emoji: "🗿",
    hp: 20,
    attack: 4,
    speed: 2,
    gold: 10,
    dropChance: 0.5,
    dropPool: ["shield_fragment"],
    cost: 4,
  },
  mimic: {
    id: "mimic",
    name: "Mimic",
    emoji: "🎁",
    hp: 12,
    attack: 4,
    speed: 1,
    gold: 8,
    dropChance: 1,
    dropPool: ["iron_blade", "golden_idol", "frost_shard", "venom_gland"],
    cost: 3,
    mimic: true,
  },
  rat_swarm: {
    id: "rat_swarm",
    name: "Rat Swarm",
    emoji: "🐀",
    hp: 3,
    attack: 1,
    speed: 1,
    gold: 1,
    dropChance: 0.15,
    dropPool: ["gold_nugget"],
    cost: 1,
    swarm: 3,
  },
};

export const ENEMY_POOL_BY_LEVEL = {
  1: ["green_blob", "green_blob", "skeleton", "rat_swarm"],
  2: ["green_blob", "skeleton", "fire_imp", "rat_swarm"],
  3: ["skeleton", "fire_imp", "stone_golem", "mimic"],
  4: ["fire_imp", "stone_golem", "stone_golem", "mimic"],
  5: ["stone_golem", "stone_golem", "mimic"],
};

/** Terminus enemies per level */
export const TERMINI = {
  1: { id: "t1", name: "Bloated Blob", emoji: "🫠", hp: 20, attack: 2, speed: 1, gold: 15, dropChance: 1, dropPool: ["flame_core", "shield_fragment"] },
  2: { id: "t2", name: "Bone Knight", emoji: "☠️", hp: 35, attack: 4, speed: 1, gold: 25, dropChance: 1, dropPool: ["rusty_sword", "shield_fragment"] },
  3: { id: "t3", name: "Ember Drake", emoji: "🐉", hp: 50, attack: 5, speed: 1, gold: 35, dropChance: 1, dropPool: ["flame_core"] },
  4: { id: "t4", name: "Ancient Golem", emoji: "🧱", hp: 70, attack: 6, speed: 2, gold: 50, dropChance: 1, dropPool: ["shield_fragment"] },
  5: { id: "t5", name: "Gelatinous King", emoji: "👑", hp: 100, attack: 7, speed: 1, gold: 100, dropChance: 1, dropPool: ["bomb"], boss: true, phase: 1, absorbed: [] },
};

/** Obstacles
 *  blocking=true means the obstacle stops at the column adjacent to the slime
 *  instead of entering the slime cell. The slime must lane-change to bypass it.
 *  Non-blocking obstacles damage the slime on contact and despawn. Blocking
 *  obstacles can be hit by other entities sliding into them (item piles, etc).
 */
export const OBSTACLES = {
  rock: { id: "rock", name: "Rock", emoji: "🪨", damage: 3, cost: 1 },
  spikes: { id: "spikes", name: "Spikes", emoji: "⚡", damage: 5, cost: 2 },
  boulder: {
    id: "boulder",
    name: "Boulder",
    emoji: "⛰️",
    damage: 8,
    blocking: true,
    cost: 3,
  },
};

/** Locations */
export const LOCATIONS = {
  fountain: { id: "fountain", name: "Fountain", emoji: "⛲", cost: 0 },
  shop: { id: "shop", name: "Shop", emoji: "🏪", cost: 0 },
  shrine: { id: "shrine", name: "Shrine", emoji: "🪬", cost: 0 },
  merchant: { id: "merchant", name: "Merchant Caravan", emoji: "🐪", cost: 0 },
  pool: { id: "pool", name: "Mysterious Pool", emoji: "🌊", cost: 0 },
  elder: { id: "elder", name: "Slime Elder", emoji: "🧙", cost: 0 },
};

/** Shop item prices by rarity */
export const SHOP_PRICES = {
  common: 8,
  uncommon: 15,
  rare: 30,
  legendary: 60,
};

/** Shrine blessings — run-long passive buffs chosen at shrines */
export const SHRINE_BLESSINGS = {
  iron_skin: { id: "iron_skin", name: "Iron Skin", desc: "-1 damage from all sources", icon: "🛡️", buff: "iron_skin" },
  swift_stomach: { id: "swift_stomach", name: "Swift Stomach", desc: "Digestion 25% faster", icon: "⚡", buff: "swift_stomach" },
  golden_touch: { id: "golden_touch", name: "Golden Touch", desc: "Enemies drop 50% more gold", icon: "✨", buff: "golden_touch" },
  vitality: { id: "vitality", name: "Vitality", desc: "+5 max HP permanently", icon: "❤️", buff: "vitality" },
  thorn_aura: { id: "thorn_aura", name: "Thorn Aura", desc: "Deal 1 damage to attackers", icon: "🌹", buff: "thorn_aura" },
};
