// SlimeVenture — data definitions
// Items, enemies, obstacles, locations. Kept data-driven per GDD §12.4.

export const RARITIES = {
  common: "C",
  uncommon: "U",
  rare: "R",
  legendary: "L",
};

/** Items — themed around slime biology, clockwork salvage, and overgrown nature. */
export const ITEMS = {
  // --- Common ---
  thorn_branch: {
    id: "thorn_branch",
    name: "Thorn Branch",
    emoji: "🌿",
    rarity: "common",
    held: { attack: 2 },
    digest: { gold: 3 },
    digestTime: 8,
    tags: ["organic"],
    flavor: "A barbed vine still dripping sap.",
  },
  healing_herb: {
    id: "healing_herb",
    name: "Mossbloom",
    emoji: "🌱",
    rarity: "common",
    held: { regen: 1, regenInterval: 5 },
    digest: { heal: 10 },
    digestTime: 3,
    tags: ["organic", "healing"],
    flavor: "A soft clump of regenerative moss.",
  },
  amber_chunk: {
    id: "amber_chunk",
    name: "Amber Chunk",
    emoji: "🟡",
    rarity: "common",
    held: null,
    digest: { gold: 15 },
    digestTime: 4,
    tags: ["mineral"],
    flavor: "Fossilized tree resin, worth good trade.",
  },
  slime_jelly: {
    id: "slime_jelly",
    name: "Slime Jelly",
    emoji: "🟣",
    rarity: "common",
    held: { maxHpBonus: 1 },
    digest: { heal: 5, permMaxHp: 1 },
    digestTime: 2,
    tags: ["organic", "slime"],
    flavor: "A quivering nodule of proto-slime.",
  },
  gear_scrap: {
    id: "gear_scrap",
    name: "Gear Scrap",
    emoji: "⚙️",
    rarity: "common",
    held: null,
    digest: { gold: 8 },
    digestTime: 5,
    tags: ["metal", "clockwork"],
    flavor: "Bent cogs from a fallen automaton.",
  },
  // --- Uncommon ---
  magma_geode: {
    id: "magma_geode",
    name: "Magma Geode",
    emoji: "🔥",
    rarity: "uncommon",
    held: { attack: 1 },
    digest: { heal: 2, buff: "burn_aura" },
    digestTime: 6,
    tags: ["elemental", "mineral"],
    flavor: "Cracked stone weeping molten light.",
  },
  clockwork_plate: {
    id: "clockwork_plate",
    name: "Clockwork Plate",
    emoji: "🛡️",
    rarity: "uncommon",
    held: { damageReduction: 1 },
    digest: { gold: 5 },
    digestTime: 10,
    tags: ["metal", "clockwork"],
    flavor: "A dented automaton chest-plate.",
  },
  spore_bomb: {
    id: "spore_bomb",
    name: "Spore Bomb",
    emoji: "💥",
    rarity: "uncommon",
    held: null,
    digest: { enemyDamage: 20 },
    digestTime: 1,
    tags: ["organic"],
    flavor: "A bloated fungal pod. Handle with care.",
  },
  toxic_mushroom: {
    id: "toxic_mushroom",
    name: "Deathcap",
    emoji: "🍄",
    rarity: "uncommon",
    held: null,
    digest: { buff: "poison_coat", heal: 1 },
    digestTime: 2,
    tags: ["organic", "poison"],
    flavor: "Speckled with iridescent toxin.",
  },
  speed_berry: {
    id: "speed_berry",
    name: "Quickvine Berry",
    emoji: "🫐",
    rarity: "uncommon",
    held: null,
    digest: { buff: "haste", heal: 2 },
    digestTime: 2,
    tags: ["organic"],
    flavor: "Pulses with kinetic sap.",
  },
  acid_vial: {
    id: "acid_vial",
    name: "Digestive Enzyme",
    emoji: "🧫",
    rarity: "uncommon",
    held: null,
    digest: { buff: "acid", heal: 1 },
    digestTime: 1,
    tags: ["organic", "slime"],
    flavor: "Concentrated slime-gut extract.",
  },
  sticky_resin: {
    id: "sticky_resin",
    name: "Pine Resin",
    emoji: "🍯",
    rarity: "uncommon",
    held: null,
    digest: { buff: "sticky", heal: 2 },
    digestTime: 2,
    tags: ["organic"],
    flavor: "Oozing amber from an ancient pine.",
  },
  spring_coil: {
    id: "spring_coil",
    name: "Mainspring Coil",
    emoji: "🔩",
    rarity: "uncommon",
    held: { attack: 2 },
    digest: { gold: 8 },
    digestTime: 7,
    tags: ["metal", "clockwork"],
    flavor: "Still wound tight. Snaps with force.",
  },
  // --- Rare ---
  vine_whip: {
    id: "vine_whip",
    name: "Vine Whip",
    emoji: "🌾",
    rarity: "rare",
    held: { attack: 4 },
    digest: { gold: 8 },
    digestTime: 10,
    tags: ["organic"],
    flavor: "A living tendril that strikes on its own.",
  },
  venom_gland: {
    id: "venom_gland",
    name: "Venom Gland",
    emoji: "🧪",
    rarity: "rare",
    held: null,
    digest: { buff: "poison_coat", heal: 3 },
    digestTime: 4,
    tags: ["organic", "poison", "slime"],
    flavor: "Harvested from a caustic cousin.",
  },
  frost_shard: {
    id: "frost_shard",
    name: "Frost-Rimed Bark",
    emoji: "🧊",
    rarity: "rare",
    held: { damageReduction: 2 },
    digest: { buff: "shield", heal: 5 },
    digestTime: 5,
    tags: ["elemental", "organic"],
    flavor: "Peeled from a frozen elder-oak.",
  },
  life_root: {
    id: "life_root",
    name: "Heartroot",
    emoji: "🌳",
    rarity: "rare",
    held: { regen: 2, regenInterval: 4 },
    digest: { heal: 20 },
    digestTime: 5,
    tags: ["organic", "healing"],
    flavor: "Throbs with the pulse of deep earth.",
  },
  golden_idol: {
    id: "golden_idol",
    name: "Gilded Gear",
    emoji: "✨",
    rarity: "rare",
    held: null,
    digest: { gold: 40 },
    digestTime: 6,
    tags: ["metal", "clockwork"],
    flavor: "An ornamental flywheel, gold-leafed.",
  },
  volatile_pod: {
    id: "volatile_pod",
    name: "Volatile Pod",
    emoji: "🧨",
    rarity: "rare",
    held: null,
    digest: { enemyDamage: 35, buff: "burn_aura" },
    digestTime: 2,
    tags: ["organic"],
    flavor: "A seedpod primed to detonate.",
  },
  thorned_carapace: {
    id: "thorned_carapace",
    name: "Thorned Carapace",
    emoji: "🦔",
    rarity: "rare",
    held: { damageReduction: 1, attack: 1 },
    digest: { gold: 6 },
    digestTime: 8,
    tags: ["organic"],
    flavor: "Shed by a creature of root and bone.",
  },
  slime_mold: {
    id: "slime_mold",
    name: "Mycelial Mass",
    emoji: "🫧",
    rarity: "rare",
    held: null,
    digest: { buff: "bloat", heal: 3 },
    digestTime: 3,
    tags: ["organic", "slime"],
    flavor: "A fungal network that expands on contact.",
  },
  automaton_core: {
    id: "automaton_core",
    name: "Automaton Core",
    emoji: "💠",
    rarity: "rare",
    held: { attack: 3, damageReduction: 1 },
    digest: { gold: 15 },
    digestTime: 12,
    tags: ["metal", "clockwork"],
    flavor: "The still-warm heart of a clockwork beast.",
  },
  // --- Legendary ---
  crystal_heart: {
    id: "crystal_heart",
    name: "Heartstone",
    emoji: "💎",
    rarity: "legendary",
    held: { maxHpBonus: 5, regen: 1, regenInterval: 6 },
    digest: { heal: 30, permMaxHp: 3 },
    digestTime: 8,
    tags: ["mineral", "healing"],
    flavor: "A living geode grown inside the earth's chest.",
  },
  worldtree_branch: {
    id: "worldtree_branch",
    name: "Worldtree Branch",
    emoji: "🌳",
    rarity: "legendary",
    held: { attack: 6 },
    digest: { enemyDamage: 50, buff: "burn_aura" },
    digestTime: 3,
    tags: ["organic"],
    flavor: "Torn from the canopy of something primordial.",
  },
  spore_phoenix: {
    id: "spore_phoenix",
    name: "Spore Phoenix",
    emoji: "🪶",
    rarity: "legendary",
    held: { regen: 3, regenInterval: 3 },
    digest: { heal: 50 },
    digestTime: 6,
    tags: ["organic", "healing"],
    flavor: "A fungal bloom that regenerates from ash.",
  },
  epoch_gear: {
    id: "epoch_gear",
    name: "Epoch Gear",
    emoji: "⏳",
    rarity: "legendary",
    held: { attack: 3, damageReduction: 3 },
    digest: { gold: 60 },
    digestTime: 12,
    tags: ["metal", "clockwork"],
    flavor: "The master-gear of a forgotten titan.",
  },
};

export const ITEM_POOL_BY_RARITY = {
  common: ["thorn_branch", "healing_herb", "amber_chunk", "slime_jelly", "gear_scrap"],
  uncommon: ["magma_geode", "clockwork_plate", "spore_bomb", "toxic_mushroom", "speed_berry", "acid_vial", "sticky_resin", "spring_coil"],
  rare: ["vine_whip", "venom_gland", "frost_shard", "life_root", "golden_idol", "volatile_pod", "thorned_carapace", "slime_mold", "automaton_core"],
  legendary: ["crystal_heart", "worldtree_branch", "spore_phoenix", "epoch_gear"],
};

/** Enemies — clockwork constructs, overgrown creatures, and rival slimes */
export const ENEMIES = {
  moss_crawler: {
    id: "moss_crawler",
    name: "Moss Crawler",
    emoji: "🐛",
    hp: 5,
    attack: 1,
    speed: 1,
    gold: 2,
    dropChance: 0,
    cost: 1,
  },
  rust_beetle: {
    id: "rust_beetle",
    name: "Rust Beetle",
    emoji: "🪲",
    hp: 7,
    attack: 2,
    speed: 1,
    gold: 3,
    dropChance: 0.3,
    dropPool: ["gear_scrap"],
    cost: 1,
  },
  gear_spider: {
    id: "gear_spider",
    name: "Gear Spider",
    emoji: "🕷️",
    hp: 10,
    attack: 3,
    speed: 1,
    gold: 5,
    dropChance: 0.3,
    dropPool: ["spring_coil"],
    cost: 2,
  },
  ember_wisp: {
    id: "ember_wisp",
    name: "Ember Wisp",
    emoji: "🔥",
    hp: 8,
    attack: 2,
    speed: 1,
    gold: 3,
    dropChance: 0.25,
    dropPool: ["magma_geode"],
    cost: 2,
    onDeath: { burn: 3 },
  },
  overgrown_golem: {
    id: "overgrown_golem",
    name: "Overgrown Golem",
    emoji: "🗿",
    hp: 20,
    attack: 4,
    speed: 2,
    gold: 10,
    dropChance: 0.5,
    dropPool: ["clockwork_plate"],
    cost: 4,
  },
  thorn_mimic: {
    id: "thorn_mimic",
    name: "Thorn Mimic",
    emoji: "🎁",
    hp: 12,
    attack: 4,
    speed: 1,
    gold: 8,
    dropChance: 1,
    dropPool: ["vine_whip", "golden_idol", "frost_shard", "venom_gland"],
    cost: 3,
    mimic: true,
  },
  spore_swarm: {
    id: "spore_swarm",
    name: "Spore Swarm",
    emoji: "🍄",
    hp: 3,
    attack: 1,
    speed: 1,
    gold: 1,
    dropChance: 0.15,
    dropPool: ["amber_chunk"],
    cost: 1,
    swarm: 3,
  },
  hornet: {
    id: "hornet",
    name: "Ironwood Hornet",
    emoji: "🐝",
    hp: 6,
    attack: 2,
    speed: 1,
    gold: 4,
    dropChance: 0.2,
    dropPool: ["speed_berry"],
    cost: 2,
    behavior: "chaser",
  },
  gilded_squirrel: {
    id: "gilded_squirrel",
    name: "Gilded Squirrel",
    emoji: "🐿️",
    hp: 8,
    attack: 0,
    speed: 1,
    gold: 20,
    dropChance: 1,
    dropPool: ["golden_idol", "amber_chunk", "amber_chunk"],
    cost: 3,
    behavior: "fleer",
    fleeTimer: 8,
  },
  vine_serpent: {
    id: "vine_serpent",
    name: "Vine Serpent",
    emoji: "🐍",
    hp: 10,
    attack: 3,
    speed: 1,
    gold: 6,
    dropChance: 0.3,
    dropPool: ["venom_gland", "toxic_mushroom"],
    cost: 3,
    behavior: "lane_switcher",
    switchInterval: 3,
  },
  clockwork_sentry: {
    id: "clockwork_sentry",
    name: "Clockwork Sentry",
    emoji: "🤖",
    hp: 14,
    attack: 3,
    speed: 2,
    gold: 7,
    dropChance: 0.4,
    dropPool: ["automaton_core", "gear_scrap"],
    cost: 3,
  },
  bark_golem: {
    id: "bark_golem",
    name: "Bark Golem",
    emoji: "🌲",
    hp: 25,
    attack: 5,
    speed: 2,
    gold: 12,
    dropChance: 0.4,
    dropPool: ["life_root", "thorned_carapace"],
    cost: 5,
  },
};

export const ENEMY_POOL_BY_LEVEL = {
  1: ["moss_crawler", "moss_crawler", "rust_beetle", "spore_swarm", "hornet"],
  2: ["moss_crawler", "rust_beetle", "gear_spider", "ember_wisp", "spore_swarm", "hornet"],
  3: ["gear_spider", "ember_wisp", "overgrown_golem", "thorn_mimic", "hornet", "vine_serpent"],
  4: ["ember_wisp", "overgrown_golem", "clockwork_sentry", "thorn_mimic", "gilded_squirrel", "vine_serpent"],
  5: ["overgrown_golem", "clockwork_sentry", "thorn_mimic", "vine_serpent", "gilded_squirrel"],
  6: ["gear_spider", "overgrown_golem", "clockwork_sentry", "vine_serpent", "bark_golem"],
  7: ["overgrown_golem", "clockwork_sentry", "thorn_mimic", "bark_golem", "gilded_squirrel"],
  8: ["clockwork_sentry", "bark_golem", "thorn_mimic", "vine_serpent", "hornet"],
  9: ["bark_golem", "clockwork_sentry", "thorn_mimic", "vine_serpent", "overgrown_golem"],
  10: ["bark_golem", "clockwork_sentry", "thorn_mimic", "vine_serpent", "gilded_squirrel"],
};

/** Terminus enemies per level — themed bosses of each biome zone */
export const TERMINI = {
  1: { id: "t1", name: "Bloated Mosslord", emoji: "🫠", hp: 20, attack: 2, speed: 1, gold: 15, dropChance: 1, dropPool: ["magma_geode", "clockwork_plate"] },
  2: { id: "t2", name: "Cogwork Centipede", emoji: "🐛", hp: 35, attack: 4, speed: 1, gold: 25, dropChance: 1, dropPool: ["spring_coil", "gear_scrap"] },
  3: { id: "t3", name: "Ember Stag", emoji: "🦌", hp: 50, attack: 5, speed: 1, gold: 35, dropChance: 1, dropPool: ["magma_geode"] },
  4: { id: "t4", name: "Rootbound Titan", emoji: "🌿", hp: 70, attack: 6, speed: 2, gold: 50, dropChance: 1, dropPool: ["life_root"] },
  5: { id: "t5", name: "Furnace Drake", emoji: "🐉", hp: 65, attack: 6, speed: 1, gold: 40, dropChance: 1, dropPool: ["magma_geode", "volatile_pod"] },
  6: { id: "t6", name: "Crystal Tortoise", emoji: "🐢", hp: 80, attack: 5, speed: 2, gold: 50, dropChance: 1, dropPool: ["frost_shard", "clockwork_plate"] },
  7: { id: "t7", name: "Mycelium Horror", emoji: "🍄", hp: 55, attack: 8, speed: 1, gold: 55, dropChance: 1, dropPool: ["venom_gland"] },
  8: { id: "t8", name: "Siege Automaton", emoji: "🤖", hp: 100, attack: 7, speed: 2, gold: 65, dropChance: 1, dropPool: ["automaton_core", "epoch_gear"] },
  9: { id: "t9", name: "Ancient Treant", emoji: "🌳", hp: 90, attack: 9, speed: 1, gold: 80, dropChance: 1, dropPool: ["worldtree_branch"] },
  10: { id: "t10", name: "The Gelatinous Sovereign", emoji: "👑", hp: 120, attack: 8, speed: 1, gold: 150, dropChance: 1, dropPool: ["crystal_heart"], boss: true, phase: 1, absorbed: [] },
};

/** Obstacles
 *  blocking=true means the obstacle stops at the column adjacent to the slime
 *  instead of entering the slime cell. The slime must lane-change to bypass it.
 *  Non-blocking obstacles damage the slime on contact and despawn. Blocking
 *  obstacles can be hit by other entities sliding into them (item piles, etc).
 */
export const OBSTACLES = {
  rock: { id: "rock", name: "Rock", emoji: "🪨", damage: 3, cost: 1 },
  spikes: { id: "spikes", name: "Spikes", emoji: "⚡", damage: 5, cost: 2 },
  boulder: {
    id: "boulder",
    name: "Boulder",
    emoji: "⛰️",
    damage: 8,
    blocking: true,
    cost: 3,
  },
};

/** Locations */
export const LOCATIONS = {
  fountain: { id: "fountain", name: "Fountain", emoji: "⛲", cost: 0 },
  shop: { id: "shop", name: "Shop", emoji: "🏪", cost: 0 },
  shrine: { id: "shrine", name: "Shrine", emoji: "🪬", cost: 0 },
  merchant: { id: "merchant", name: "Merchant Caravan", emoji: "🐪", cost: 0 },
  pool: { id: "pool", name: "Mysterious Pool", emoji: "🌊", cost: 0 },
  elder: { id: "elder", name: "Slime Elder", emoji: "🧙", cost: 0 },
};

/** Shop item prices by rarity */
export const SHOP_PRICES = {
  common: 8,
  uncommon: 15,
  rare: 30,
  legendary: 60,
};

/** Shrine blessings — run-long passive buffs chosen at shrines */
export const SHRINE_BLESSINGS = {
  iron_skin: { id: "iron_skin", name: "Bark Plating", desc: "-1 damage from all sources", icon: "🌿", buff: "iron_skin" },
  swift_stomach: { id: "swift_stomach", name: "Mycelial Surge", desc: "Digestion 25% faster", icon: "🍄", buff: "swift_stomach" },
  golden_touch: { id: "golden_touch", name: "Midas Moss", desc: "Enemies drop 50% more gold", icon: "✨", buff: "golden_touch" },
  vitality: { id: "vitality", name: "Heartwood Bond", desc: "+5 max HP permanently", icon: "🌳", buff: "vitality" },
  thorn_aura: { id: "thorn_aura", name: "Briar Ward", desc: "Deal 1 damage to attackers", icon: "🌹", buff: "thorn_aura" },
  gearmind: { id: "gearmind", name: "Gearmind", desc: "+1 attack permanently", icon: "⚙️", buff: "gearmind" },
};
