// SlimeVenture — Run Map
// Slay-the-Spire-style branching path generator + SVG renderer.
//
// A run is a 5-row grid of nodes:
//   row 0:        [start]
//   rows 1-3:  [n] [n] [n]   (3 wide, branching)
//   row 4:        [boss]
//
// Paths are generated by walking from the start to the boss several times,
// each pass picking adjacent columns. Nodes touched by any path become
// "active" and get a type. Edges are stored on the source node as a Set of
// destination column indices in the next row.

export const NODE_TYPES = {
  start: {
    label: "Start",
    emoji: "🟢",
    color: "#5cb85c",
    spawnWeights: { enemy: 0.45, item: 0.30, obstacle: 0.15, location: 0.10 },
    tickLength: 30,
  },
  combat: {
    label: "Combat",
    emoji: "⚔️",
    color: "#d9534f",
    spawnWeights: { enemy: 0.65, item: 0.15, obstacle: 0.15, location: 0.05 },
    tickLength: 42,
  },
  treasure: {
    label: "Treasure",
    emoji: "💎",
    color: "#f0ad4e",
    spawnWeights: { enemy: 0.20, item: 0.60, obstacle: 0.15, location: 0.05 },
    tickLength: 32,
  },
  event: {
    label: "Event",
    emoji: "❓",
    color: "#5bc0de",
    spawnWeights: { enemy: 0.30, item: 0.20, obstacle: 0.10, location: 0.40 },
    tickLength: 36,
  },
  elite: {
    label: "Elite",
    emoji: "⭐",
    color: "#bb6bd9",
    spawnWeights: { enemy: 0.60, item: 0.20, obstacle: 0.15, location: 0.05 },
    tickLength: 46,
    terminusHpMult: 1.6,
    terminusAtkBonus: 1,
    terminusGoldMult: 2,
  },
  boss: {
    label: "Boss",
    emoji: "👑",
    color: "#f5c518",
    spawnWeights: { enemy: 0.55, item: 0.20, obstacle: 0.20, location: 0.05 },
    tickLength: 50,
  },
};

const ROW_WIDTHS = [1, 3, 3, 3, 1];
const NUM_PATHS = 5;
const MIDDLE_TYPE_BAG = ["combat", "combat", "treasure", "event"];
const PRE_BOSS_TYPE_BAG = ["combat", "elite", "elite", "event", "treasure"];

function rand(n) {
  return Math.floor(Math.random() * n);
}
function pick(arr) {
  return arr[rand(arr.length)];
}

export function generateRunMap() {
  const rows = ROW_WIDTHS.length;
  const grid = [];
  for (let r = 0; r < rows; r++) {
    const w = ROW_WIDTHS[r];
    const row = [];
    for (let c = 0; c < w; c++) {
      row.push({
        row: r,
        col: c,
        type: null,
        active: r === 0 || r === rows - 1, // start + boss always active
        edges: new Set(),
      });
    }
    grid.push(row);
  }

  // Walk NUM_PATHS times from start to boss, marking edges.
  for (let p = 0; p < NUM_PATHS; p++) {
    let col = rand(grid[1].length);
    grid[0][0].edges.add(col);
    grid[1][col].active = true;
    for (let r = 1; r < rows - 1; r++) {
      const nextWidth = grid[r + 1].length;
      let target;
      if (r + 1 === rows - 1) {
        target = 0; // boss column
      } else {
        // Adjacent column, clamped to grid
        const choices = [col - 1, col, col + 1].filter(
          (x) => x >= 0 && x < nextWidth
        );
        target = pick(choices);
      }
      grid[r][col].edges.add(target);
      grid[r + 1][target].active = true;
      col = target;
    }
  }

  // Assign types to every active node.
  for (let r = 0; r < rows; r++) {
    for (const node of grid[r]) {
      if (!node.active) continue;
      if (r === 0) {
        node.type = "start";
      } else if (r === rows - 1) {
        node.type = "boss";
      } else if (r === rows - 2) {
        node.type = pick(PRE_BOSS_TYPE_BAG);
      } else {
        node.type = pick(MIDDLE_TYPE_BAG);
      }
    }
  }

  // Guarantee at least one elite somewhere in the middle rows.
  let hasElite = false;
  for (let r = 1; r < rows - 1; r++) {
    for (const n of grid[r]) {
      if (n.active && n.type === "elite") hasElite = true;
    }
  }
  if (!hasElite) {
    const candidates = [];
    for (let r = 1; r < rows - 1; r++) {
      for (const n of grid[r]) {
        if (n.active && n.type !== "elite") candidates.push(n);
      }
    }
    if (candidates.length > 0) pick(candidates).type = "elite";
  }

  return grid;
}

export function getNextNodes(map, row, col) {
  if (!map || row >= map.length - 1) return [];
  const node = map[row] && map[row][col];
  if (!node) return [];
  const next = [];
  for (const c of node.edges) {
    const target = map[row + 1] && map[row + 1][c];
    if (target) next.push(target);
  }
  return next;
}

// ---------- SVG renderer ----------

const SVG_NS = "http://www.w3.org/2000/svg";
const VIEW_WIDTH = 280;
const ROW_HEIGHT = 58;
const NODE_RADIUS = 19;

function nodeX(col, rowWidth) {
  return (VIEW_WIDTH / (rowWidth + 1)) * (col + 1);
}
function nodeY(row) {
  return row * ROW_HEIGHT + NODE_RADIUS + 6;
}

export function renderMapSVG(map, currentRow, currentCol, onSelectNode) {
  const rows = map.length;
  const height = rows * ROW_HEIGHT + 12;

  const svg = document.createElementNS(SVG_NS, "svg");
  svg.setAttribute("viewBox", `0 0 ${VIEW_WIDTH} ${height}`);
  svg.setAttribute("class", "map-svg");

  const nextNodes = getNextNodes(map, currentRow, currentCol);
  const reachable = new Set(nextNodes.map((n) => `${n.row}:${n.col}`));

  // ---- Edges (drawn first, behind nodes) ----
  for (let r = 0; r < rows - 1; r++) {
    const widthR = map[r].length;
    const widthN = map[r + 1].length;
    for (const node of map[r]) {
      if (!node.active) continue;
      for (const tCol of node.edges) {
        const target = map[r + 1][tCol];
        if (!target) continue;
        const x1 = nodeX(node.col, widthR);
        const y1 = nodeY(r) + NODE_RADIUS - 2;
        const x2 = nodeX(tCol, widthN);
        const y2 = nodeY(r + 1) - NODE_RADIUS + 2;
        const isLive = r === currentRow && node.col === currentCol;
        const isPast = r < currentRow;

        const line = document.createElementNS(SVG_NS, "line");
        line.setAttribute("x1", x1);
        line.setAttribute("y1", y1);
        line.setAttribute("x2", x2);
        line.setAttribute("y2", y2);
        if (isLive) {
          line.setAttribute("class", "map-edge live");
        } else if (isPast) {
          line.setAttribute("class", "map-edge past");
        } else {
          line.setAttribute("class", "map-edge");
        }
        svg.appendChild(line);
      }
    }
  }

  // ---- Nodes ----
  for (let r = 0; r < rows; r++) {
    const widthR = map[r].length;
    for (const node of map[r]) {
      if (!node.active) continue;
      const cfg = NODE_TYPES[node.type] || NODE_TYPES.combat;
      const x = nodeX(node.col, widthR);
      const y = nodeY(r);

      const isCurrent = r === currentRow && node.col === currentCol;
      const isReachable = reachable.has(`${r}:${node.col}`);
      const isPast = r < currentRow;

      const g = document.createElementNS(SVG_NS, "g");
      g.setAttribute("transform", `translate(${x},${y})`);
      let cls = "map-node";
      if (isCurrent) cls += " current";
      else if (isReachable) cls += " reachable";
      else if (isPast) cls += " past";
      else cls += " locked";
      g.setAttribute("class", cls);

      const circle = document.createElementNS(SVG_NS, "circle");
      circle.setAttribute("r", NODE_RADIUS);
      circle.setAttribute("fill", cfg.color);
      g.appendChild(circle);

      const text = document.createElementNS(SVG_NS, "text");
      text.setAttribute("text-anchor", "middle");
      text.setAttribute("dominant-baseline", "central");
      text.setAttribute("y", "1");
      text.setAttribute("font-size", "20");
      text.textContent = cfg.emoji;
      g.appendChild(text);

      if (isReachable && onSelectNode) {
        g.addEventListener("click", () => onSelectNode(node));
      }

      svg.appendChild(g);
    }
  }

  return svg;
}
